inputs = [
    [{ x = "301466" }, { x = "222822" }, { x = "91750" }, { x = "19661" }],
    [{ x = "412877" }, { x = "216269" }, { x = "393216" }, { x = "163840" }],
    [{ x = "301466" }, { x = "235930" }, { x = "65536" }, { x = "13107" }],
    [{ x = "353894" }, { x = "196608" }, { x = "294912" }, { x = "98304" }],
    [{ x = "471859" }, { x = "196608" }, { x = "380109" }, { x = "104858" }],
    [{ x = "321126" }, { x = "163840" }, { x = "294912" }, { x = "111411" }],
    [{ x = "458752" }, { x = "209715" }, { x = "308019" }, { x = "91750" }],
    [{ x = "334234" }, { x = "222822" }, { x = "98304" }, { x = "13107" }],
    [{ x = "380109" }, { x = "176947" }, { x = "268698" }, { x = "65536" }],
    [{ x = "308019" }, { x = "209715" }, { x = "104858" }, { x = "13107" }],
    [{ x = "419430" }, { x = "209715" }, { x = "347341" }, { x = "150733" }],
    [{ x = "452198" }, { x = "203162" }, { x = "334234" }, { x = "150733" }],
    [{ x = "425984" }, { x = "196608" }, { x = "380109" }, { x = "144179" }],
    [{ x = "367002" }, { x = "196608" }, { x = "268698" }, { x = "85197" }],
    [{ x = "406323" }, { x = "222822" }, { x = "353894" }, { x = "150733" }],
    [{ x = "327680" }, { x = "229376" }, { x = "104858" }, { x = "39322" }],
    [{ x = "301466" }, { x = "235930" }, { x = "65536" }, { x = "13107" }],
    [{ x = "308019" }, { x = "209715" }, { x = "85197" }, { x = "13107" }],
    [{ x = "373555" }, { x = "288358" }, { x = "98304" }, { x = "26214" }],
    [{ x = "399770" }, { x = "170394" }, { x = "367002" }, { x = "91750" }],
    [{ x = "373555" }, { x = "288358" }, { x = "98304" }, { x = "26214" }],
    [{ x = "445645" }, { x = "196608" }, { x = "360448" }, { x = "137626" }],
    [{ x = "452198" }, { x = "203162" }, { x = "353894" }, { x = "137626" }],
    [{ x = "314573" }, { x = "203162" }, { x = "104858" }, { x = "13107" }],
    [{ x = "367002" }, { x = "163840" }, { x = "255590" }, { x = "72090" }],
    [{ x = "471859" }, { x = "209715" }, { x = "393216" }, { x = "117965" }],
    [{ x = "373555" }, { x = "183501" }, { x = "294912" }, { x = "85197" }],
    [{ x = "353894" }, { x = "222822" }, { x = "111411" }, { x = "13107" }],
    [{ x = "425984" }, { x = "196608" }, { x = "360448" }, { x = "117965" }],
    [{ x = "471859" }, { x = "235930" }, { x = "399770" }, { x = "163840" }]
]

labels = [
    [{ x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }],
    [{ x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }],
    [{ x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }]
]